name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "0 3 * * 0" # every Sunday at 3am


jobs:
  build:
    name: "${{matrix.os }} - Node ${{ matrix.node }}"
    runs-on: "${{ matrix.os }}-latest"

    strategy:
      matrix:
        node: [14, 16]
        os: [windows, ubuntu]

    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
      with:
        node-version: ${{ matrix.node }}

    - run: yarn install --frozen-lockfile
    - run: yarn test
